apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
      - name: discovery
        image: kennegervais/new-discovery:latest
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              key: SPRING_CONFIG_IMPORT
              name: discovery-server-config

---
apiVersion: v1
kind: Service
metadata:
  name: discovery
spec:
  selector:
    app: discovery-server
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-server-config
data:
  SPRING_CONFIG_IMPORT: "optional:configserver:http://discovery.default.svc.cluster.local:8888"