spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:password@localhost:27017/product_service?authSource=admin}
  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.1.13:8181/realms/spring-microservices-security-realm/protocol/openid-connect/certs

management:
  observations:
    key-values:
      application: product-service