eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      override-system-properties: false

gateway:
  service:
    url: http://localhost:9000
    name: API-GATEWAY

product:
  service:
    url: http://localhost:8080
    name: PRODUCT-SERVICE

order:
  service:
    url: http://localhost:8081
    name: ORDER-SERVICE

inventory:
  service:
    url: http://localhost:8082
    name: INVENTORY-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: order-service
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

# Loki URL
loki:
  url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}